### ISSUE TITLE
Not reloading in OBS 

### ISSUE THREAD

**Issue by TeaSpillStudios** [ComputerElite/streamer-tools-client#2]
In OBS. The website does not seem to request a refresh. And the overlay does not change till I press refresh on the browser source

**Comment by ComputerElite** [comment]
Does this happen with all overlays or only one? Also what does the overlay display? Does it display quest disconnected or the actual score

**Comment by TeaSpillStudios** [comment]
(IN OBS)
![image](https://user-images.githubusercontent.com/57747851/148079559-571c553b-6f08-436c-9ab6-53cce35dc3e0.png)

(IN STREAM CLIENT TOOLS)
![image](https://user-images.githubusercontent.com/57747851/148079606-cdf182f7-5880-4e5f-8557-4192ae06580c.png)

If I press reload in obs it syncs with streamer client tools

**Comment by TeaSpillStudios** [comment]
The overlay shows quest data and it happens with all overlays

**Comment by ComputerElite** [comment]
That's weird. I'll check what happens with my Quest

**Comment by TeaSpillStudios** [comment]
By the way this is all quest 1.

**Comment by ComputerElite** [comment]
Quest version doesn't matter on almost everything

**Comment by ComputerElite** [comment]
So everything is working for me. Not sure what is happening to you

**Comment by ComputerElite** [comment]
Maybe update all overlays in the downloads section

**Comment by auggeeo** [comment]
At the end of the url add "&alwaysupdate=true" (without quotes)

**Comment by ComputerElite** [comment]
If that helps it wouldn't really make sense

**Comment by ComputerElite** [comment]
The only thing alwaysupdate does is refreshing the overlay in the main menu and multiplayer menu which only shows which songs are currently selected

**Comment by auggeeo** [comment]
It did that to me also then I looked through the Js code and saw always update and that it looked for it in the url and I look more and then added true to it and it worked.

**Comment by ComputerElite** [comment]
weird. Cause if that helps the location detection is broken

**Comment by auggeeo** [comment]
Here I will show you but I have to reinstall obs on Mac because I use two computer and I do that because my windows laptop does not have that much power

**Comment by ComputerElite** [comment]
once you got it setup send me `http://[Your Quests ip]:53502/data` as well

**Comment by auggeeo** [comment]
Ok

**Comment by auggeeo** [comment]
I also made my own custom overlay should i use that?

**Comment by ComputerElite** [comment]
with my code or entirely your own?

**Comment by auggeeo** [comment]
Your code but I edited it a little bit because some of it was not working it was because of some classes I just added those in the overlay html

**Comment by ComputerElite** [comment]
Sure use it. What didn't work?

**Comment by auggeeo** [comment]
Some classes were not added in song 3 to the item elements

**Comment by ComputerElite** [comment]
oh so you used the overlay builder

**Comment by ComputerElite** [comment]
oh gosh I see my dumb head doing classes wrong, I'll fix it

**Comment by CoopPlayzz** [comment]
The casting will be square because I made one real quick

**Comment by CoopPlayzz** [comment]
ok i will post in a sec

**Comment by CoopPlayzz** [comment]
i need to restart to get data real quick

**Comment by CoopPlayzz** [comment]
quest dont want to listen to internet lol it will connect then will say no internet

**Comment by auggeeo** [comment]
sorry i could not get data

**Comment by auggeeo** [comment]
internet on quest was not liking me at the time for some reason lol

**Comment by auggeeo** [comment]
https://drive.google.com/file/d/1xC5M0efVfydLA4yzBV8A_kjNIMR_Xti-/view?usp=sharing
the video was too big

**Comment by ComputerElite** [comment]
I mean that's exactly what's supposed to happen

**Comment by ComputerElite** [comment]
if you go into a song without alwaysupdate it should update

**Comment by ComputerElite** [comment]
![image](https://user-images.githubusercontent.com/71177995/149673181-e3c782b7-4f00-449e-9e22-486aa01d29d2.png)
This enables alwaysupdate in the client

**Comment by auggeeo** [comment]
wait the the heck I swear it was enabled in the settings but for me it was not

**Comment by ComputerElite** [comment]
you mean like in game?

**Comment by auggeeo** [comment]
no in client

**Comment by ComputerElite** [comment]
the client only generates urls. If you change the settings you have to update the url in obs

**Comment by ComputerElite** [comment]
actually I think it's different. Let me check the current code

**Comment by ComputerElite** [comment]
settings should apply if you refresh in obs

**Comment by ComputerElite** [comment]
like the url the client gives you is a redirect by the client which applies the current settings

**Comment by auggeeo** [comment]
im just using my web browser at the moment but my quest still don't want wifi lol

**Comment by ComputerElite** [comment]
we can't really do anythin about that

**Comment by auggeeo** [comment]
yep

**Comment by auggeeo** [comment]
restarting wifi

**Comment by auggeeo** [comment]
im back I just got my oculus pin glitch

**Comment by auggeeo** [comment]
I enabled song select on client and in settings on oculus mod and it doesn't update automatically

**Comment by ComputerElite** [comment]
yeah syncing settings between client and mod is weird and doesn't work reliably

**Comment by auggeeo** [comment]
but it does not work on client I have to add "&alwaysupdate=true" to the url for it to work

**Comment by ComputerElite** [comment]
what's the url you got in obs?

**Comment by auggeeo** [comment]
I will just give thebandoot overly example but I got: [editing on other pc]

**Comment by auggeeo** [comment]
oh wait now it adds it

**Comment by ComputerElite** [comment]
yeah if you reload it does

**Comment by auggeeo** [comment]
I saved the it redirected me. to in my browser lol

**Comment by ComputerElite** [comment]
if it redirects you everything is allright. No need to send it

**Comment by auggeeo** [comment]
sorry for the spaces that's one thing I hate about apple butterfly. keyboard
I ment periods

**Comment by auggeeo** [comment]
also did you fix class thing if you. did not here is the. song three overlay: [edit:oh gosh github i wanted to not make it html code]

**Comment by ComputerElite** [comment]
woops forgot to push

**Comment by ComputerElite** [comment]
alright you should be able to update the overlays now

**Comment by auggeeo** [comment]
k

**Comment by auggeeo** [comment]
also is the html for the overlays private?

**Comment by ComputerElite** [comment]
https://github.com/ComputerElite/ComputerElite.github.io/tree/main/tools/Streamer_Tools_Quest_Overlay

**Comment by auggeeo** [comment]
oh thanks

**Comment by ComputerElite** [comment]
https://github.com/ComputerElite/ComputerElite.github.io/blob/main/tools/Streamer_Tools_Quest_Overlay/overlays.json That's what the client checks
