### ISSUE TITLE
Song Requests on twitch always come back as not found

### ISSUE THREAD

**Issue by auggeeo** [ComputerElite/streamer-tools-client#4]
My Twitch request always respond with not found.
Edit:
Picture: ![Pic](https://user-images.githubusercontent.com/73203995/149793201-2d703cfd-1ee9-4433-baab-d6bf551205fe.png)
[Beat Saber map](https://beatsaver.com/maps/11cf8)

**Comment by ComputerElite** [comment]
I thought I fixed that I'll look into it later

**Comment by auggeeo** [comment]
ok

**Comment by auggeeo** [comment]
here is the pic:
![Pic](https://user-images.githubusercontent.com/73203995/149793201-2d703cfd-1ee9-4433-baab-d6bf551205fe.png)

**Comment by ComputerElite** [comment]
Oh gosh it's that error with the ssl certificate. I waasn't able to fix that last time. I'll see what I can do

**Comment by ComputerElite** [comment]
![image](https://user-images.githubusercontent.com/71177995/149799917-9e92d8a6-faef-4317-9e6d-b6b8aa92c03a.png)
seems like I fixed it. You should be able to download the fix here once finsihed https://github.com/ComputerElite/streamer-tools-client/actions/runs/1708776726

**Comment by ComputerElite** [comment]
actually give me a min to fix my action script .-.

**Comment by auggeeo** [comment]
ok

**Comment by auggeeo** [comment]
also with overley builder the default .png is not in there so you will want to fix that too

**Comment by ComputerElite** [comment]
alright added it

**Comment by ComputerElite** [comment]
https://github.com/ComputerElite/streamer-tools-client/actions/runs/1708804658 There we go. Report if it works now

**Comment by auggeeo** [comment]
yep downloading it now. Also are you gonna add it as a bug fix update?

**Comment by ComputerElite** [comment]
yeah if you report that it worked

**Comment by auggeeo** [comment]
ok

**Comment by auggeeo** [comment]
Have not tested bot yet but logo shows this time insted of eletron logo

**Comment by ComputerElite** [comment]
not sure but iirc it depends on if you download the installer or the zip

**Comment by auggeeo** [comment]
it does add it but can't remove it

**Comment by ComputerElite** [comment]
wdym?

**Comment by ComputerElite** [comment]
ah

**Comment by auggeeo** [comment]
like it works but in app you can't remove the request

**Comment by ComputerElite** [comment]
should be fixed https://github.com/ComputerElite/streamer-tools-client/actions/runs/1708876713

**Comment by auggeeo** [comment]
k

**Comment by auggeeo** [comment]
it works

**Comment by ComputerElite** [comment]
great! I'll push the update shortly

**Comment by auggeeo** [comment]
ok

**Comment by auggeeo** [comment]
also i made a shields.io thing just for fun: [![Download ](https://img.shields.io/github/downloads/ComputerElite/streamer-tools-client/total?label=Download%20Today%20|%20Downloads:&logo=github&style=for-the-badge)](https://github.com/ComputerElite/streamer-tools-client/releases/latest)
[![Download ](https://img.shields.io/github/downloads/ComputerElite/streamer-tools-client/total?label=Click%20Here%20to%20Download%20|%20Downloads:&logo=github&style=for-the-badge)](https://github.com/ComputerElite/streamer-tools-client/releases/latest)
