### ISSUE TITLE
What does the twitch bot do and how can I test if it works?

### ISSUE THREAD

**Issue by HPSURV1V4L** [ComputerElite/streamer-tools-client#5]
What are the commands the twitch bot reacts to, or is it supposed to send a message when I start a new song?

**Comment by CoopPlayzz** [comment]
It’s !bsr
That’s the song request


#cooptheloop
@CoopsCards - YouTube
@TwoSchwartingCousins - YouTube


From: HPSURV1V4L
Sent: Tuesday, February 8, 2022 5:29 PM
To: ComputerElite/streamer-tools-client
Cc: Subscribed
Subject: [ComputerElite/streamer-tools-client] What does the twitch bot do and how can I test if it works? (Issue #5)

What are the commands the twitch bot reacts to, or is it supposed to send a message when I start a new song?

**Comment by auggeeo** [comment]
1.It’s !bsr
That’s the song request
2. go onto beatsaver.com and get a beat map by clicking the twitch icon and pasting it in to chat

sorry about that last msg i did it from email and it included that for some reason

**Comment by HPSURV1V4L** [comment]
Thank you! I've never used anything like it before so I had no idea.
