### ISSUE TITLE
Mac Version

### ISSUE THREAD

**Issue by OfficialJamestheFlames** [ComputerElite/streamer-tools-client#6]
`enhancement`
Ever since I couldn't pay for Parallels Desktop _(which allows you to run windows 11, 10, 8, etc on mac)_
I've been pretty bummed that I can't use this anymore. People have probably asked this before but may y'all please make a version that runs on the Mac version of OBS, the Mac version of StreamLabs, and/or the Mac version of Twitch Studio. 
Thank you guys so much!
-Sincerely,
JamestheFlames

**Comment by ComputerElite** [comment]
Hi, the readme has instructions how to run it on Mac https://github.com/ComputerElite/streamer-tools-client#mac-windows-and-linux

**Comment by OfficialJamestheFlames** [comment]
Thank you so much
