### ISSUE TITLE
"Creating a token for you own twitch account" link doesn't let me sign in. It gives an error that says "Your browser is not currently supported.

### ISSUE THREAD

**Issue by MrRecruitMan** [ComputerElite/streamer-tools-client#8]

**Comment by MrRecruitMan** [comment]
This happened on the "streamer tools client" home page when I attempted to get a twitch bot token. any support or guidance would be much appreciated. thanks

**Comment by ComputerElite** [comment]
Here's the link it opens: https://twitchapps.com/tmi/
You could try opening that in another browser on your pc and getting a token that way

**Comment by MrRecruitMan** [comment]
It worked! thank you
